In [ ]:
%cd nn

In [4]:
import numpy as np
import torch


In [5]:
data = [[1,2,3],[4,5,6]]
arr = np.array (data)
tns = torch.tensor(data)

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
tns

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
tns[1]

tensor([4, 5, 6])

In [9]:
tns[:, 1]

tensor([2, 5])

In [10]:
tns[1,1]

tensor(5)

In [11]:
tns[:, 0]

tensor([1, 4])

In [12]:
tns[1, 1:3]

tensor([5, 6])

In [14]:
tns += 1

In [19]:
tns / 1

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [20]:
tns.type()

'torch.LongTensor'

In [21]:
tns * .1

tensor([[0.2000, 0.3000, 0.4000],
        [0.5000, 0.6000, 0.7000]])

In [ ]:
t = torch.rand(4, 8, 8)
t.unsqueeze(0).shape  

In [ ]:
t.unsqueeze(1).shape  